WORDS_DICT=[
    {'word': 'a', 'partsOfSpeech': ['article']},
    {'word': 'ability', 'partsOfSpeech': ['noun']},
    {'word': 'able', 'partsOfSpeech': ['adjective']},
    {'word': 'about', 'partsOfSpeech': ['adjective', 'adverb', 'preposition']},
    {'word': 'above', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'preposition']},
    {'word': 'accept', 'partsOfSpeech': ['verb', 'adjective']},
    {'word': 'according', 'partsOfSpeech': ['verb', 'adjective', 'adverb']},
    {'word': 'account', 'partsOfSpeech': ['noun']},
    {'word': 'across', 'partsOfSpeech': ['noun', 'adverb', 'preposition']},
    {'word': 'act', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'action', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'activity', 'partsOfSpeech': ['noun']},
    {'word': 'actually', 'partsOfSpeech': ['adverb']},
    {'word': 'add', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'address', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'administration', 'partsOfSpeech': ['noun']},
    {'word': 'admit', 'partsOfSpeech': ['verb']},
    {'word': 'adult', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'affect', 'partsOfSpeech': ['verb']},
    {'word': 'after', 'partsOfSpeech': ['adjective', 'adverb', 'preposition', 'conjunction']},
    {'word': 'again', 'partsOfSpeech': ['adverb', 'preposition']},
    {'word': 'against', 'partsOfSpeech': ['preposition', 'conjunction']},
    {'word': 'age', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'agency', 'partsOfSpeech': ['noun']},
    {'word': 'agent', 'partsOfSpeech': ['noun']},
    {'word': 'ago', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'agree', 'partsOfSpeech': ['verb']},
    {'word': 'agreement', 'partsOfSpeech': ['noun']},
    {'word': 'ahead', 'partsOfSpeech': ['adverb']},
    {'word': 'air', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'all', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'pronoun', 'conjunction']},
    {'word': 'allow', 'partsOfSpeech': ['verb']},
    {'word': 'almost', 'partsOfSpeech': ['noun', 'adverb']},
    {'word': 'alone', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'along', 'partsOfSpeech': ['adverb', 'preposition']},
    {'word': 'already', 'partsOfSpeech': ['adverb']},
    {'word': 'also', 'partsOfSpeech': ['adverb']},
    {'word': 'although', 'partsOfSpeech': ['conjunction']},
    {'word': 'always', 'partsOfSpeech': ['adverb']},
    {'word': 'among', 'partsOfSpeech': ['preposition']},
    {'word': 'amount', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'analysis', 'partsOfSpeech': ['noun']},
    {'word': 'and', 'partsOfSpeech': ['noun', 'conjunction']},
    {'word': 'animal', 'partsOfSpeech': ['noun']},
    {'word': 'another', 'partsOfSpeech': ['pronoun']},
    {'word': 'answer', 'partsOfSpeech': ['noun']},
    {'word': 'any', 'partsOfSpeech': ['adverb', 'pronoun']},
    {'word': 'anyone', 'partsOfSpeech': ['pronoun']},
    {'word': 'anything', 'partsOfSpeech': ['noun', 'pronoun']},
    {'word': 'appear', 'partsOfSpeech': ['verb']},
    {'word': 'apply', 'partsOfSpeech': ['verb']},
    {'word': 'approach', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'area', 'partsOfSpeech': ['noun']},
    {'word': 'argue', 'partsOfSpeech': ['verb']},
    {'word': 'arm', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'around', 'partsOfSpeech': ['adjective', 'adverb', 'preposition']},
    {'word': 'arrive', 'partsOfSpeech': ['verb']},
    {'word': 'art', 'partsOfSpeech': ['noun']},
    {'word': 'article', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'artist', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'as', 'partsOfSpeech': ['adverb', 'preposition', 'conjunction']},
    {'word': 'ask', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'assume', 'partsOfSpeech': ['verb']},
    {'word': 'at', 'partsOfSpeech': ['verb', 'noun', 'preposition']},
    {'word': 'attack', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'attention', 'partsOfSpeech': ['noun', 'interjection']},
    {'word': 'attorney', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'audience', 'partsOfSpeech': ['noun']},
    {'word': 'author', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'authority', 'partsOfSpeech': ['noun']},
    {'word': 'available', 'partsOfSpeech': ['adjective']},
    {'word': 'avoid', 'partsOfSpeech': ['verb']},
    {'word': 'away', 'partsOfSpeech': ['verb', 'adjective', 'adverb', 'interjection']},
    {'word': 'baby', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'back', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'bad', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'bag', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'ball', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'bank', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'bar', 'partsOfSpeech': ['noun']},
    {'word': 'base', 'partsOfSpeech': ['noun', 'verb', 'noun', 'noun']},
    {'word': 'beat', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'beautiful', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'because', 'partsOfSpeech': ['adverb', 'preposition', 'conjunction']},
    {'word': 'become', 'partsOfSpeech': ['verb']},
    {'word': 'bed', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'before', 'partsOfSpeech': ['adverb', 'preposition', 'conjunction']},
    {'word': 'begin', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'behavior', 'partsOfSpeech': ['noun']},
    {'word': 'behind', 'partsOfSpeech': ['noun', 'adverb', 'preposition']},
    {'word': 'believe', 'partsOfSpeech': ['verb']},
    {'word': 'benefit', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'best', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adjective', 'adverb']},
    {'word': 'better', 'partsOfSpeech': ['noun', 'adjective', 'adjective', 'adjective', 'adverb']},
    {'word': 'between', 'partsOfSpeech': ['noun', 'preposition']},
    {'word': 'beyond', 'partsOfSpeech': ['noun', 'adverb', 'preposition']},
    {'word': 'big', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'bill', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'billion', 'partsOfSpeech': ['noun']},
    {'word': 'bit', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'black', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'blood', 'partsOfSpeech': ['noun', 'noun', 'verb']},
    {'word': 'blue', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'board', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'body', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'book', 'partsOfSpeech': ['noun']},
    {'word': 'born', 'partsOfSpeech': ['verb', 'adjective']},
    {'word': 'both', 'partsOfSpeech': ['pronoun', 'conjunction']},
    {'word': 'box', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'boy', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'break', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'bring', 'partsOfSpeech': ['verb']},
    {'word': 'brother', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'budget', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'build', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'building', 'partsOfSpeech': ['noun']},
    {'word': 'business', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'but', 'partsOfSpeech': ['noun', 'verb', 'adverb', 'preposition', 'conjunction']},
    {'word': 'buy', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'by', 'partsOfSpeech': ['noun', 'noun', 'noun', 'noun', 'noun', 'adjective', 'adverb', 'preposition', 'noun', 'interjection']},
    {'word': 'call', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'camera', 'partsOfSpeech': ['noun']},
    {'word': 'campaign', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'can', 'partsOfSpeech': ['verb']},
    {'word': 'cancer', 'partsOfSpeech': ['noun']},
    {'word': 'candidate', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'capital', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'car', 'partsOfSpeech': ['noun']},
    {'word': 'card', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'care', 'partsOfSpeech': ['noun']},
    {'word': 'career', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'carry', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'case', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'catch', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'cause', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'cell', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'center', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'central', 'partsOfSpeech': ['adjective']},
    {'word': 'century', 'partsOfSpeech': ['noun']},
    {'word': 'certain', 'partsOfSpeech': ['noun', 'adjective', 'pronoun']},
    {'word': 'certainly', 'partsOfSpeech': ['adverb']},
    {'word': 'chair', 'partsOfSpeech': ['noun', 'verb', 'noun', 'noun']},
    {'word': 'challenge', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'chance', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'change', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'character', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'charge', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'check', 'partsOfSpeech': ['noun']},
    {'word': 'child', 'partsOfSpeech': ['noun', 'noun']},
    {'word': 'choice', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'choose', 'partsOfSpeech': ['verb', 'conjunction']},
    {'word': 'church', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'citizen', 'partsOfSpeech': ['noun']},
    {'word': 'city', 'partsOfSpeech': ['noun']},
    {'word': 'civil', 'partsOfSpeech': ['adjective']},
    {'word': 'claim', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'class', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'clear', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'clearly', 'partsOfSpeech': ['adverb']},
    {'word': 'close', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'coach', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'cold', 'partsOfSpeech': ['adjective']},
    {'word': 'collection', 'partsOfSpeech': ['noun']},
    {'word': 'college', 'partsOfSpeech': ['noun']},
    {'word': 'color', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'come', 'partsOfSpeech': ['noun', 'verb', 'preposition', 'interjection']},
    {'word': 'commercial', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'common', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'community', 'partsOfSpeech': ['noun']},
    {'word': 'company', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'compare', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'computer', 'partsOfSpeech': ['noun']},
    {'word': 'concern', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'condition', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'conference', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'congress', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'consider', 'partsOfSpeech': ['verb']},
    {'word': 'consumer', 'partsOfSpeech': ['noun']},
    {'word': 'contain', 'partsOfSpeech': ['verb']},
    {'word': 'continue', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'control', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'cost', 'partsOfSpeech': ['verb']},
    {'word': 'could', 'partsOfSpeech': ['verb', 'noun']},
    {'word': 'country', 'partsOfSpeech': ['noun', 'adjective', 'noun']},
    {'word': 'couple', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'course', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'court', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'cover', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'create', 'partsOfSpeech': ['verb', 'adjective']},
    {'word': 'crime', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'cultural', 'partsOfSpeech': ['adjective']},
    {'word': 'culture', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'cup', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'current', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'customer', 'partsOfSpeech': ['noun']},
    {'word': 'cut', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'dark', 'partsOfSpeech': ['adjective']},
    {'word': 'data', 'partsOfSpeech': ['noun']},
    {'word': 'daughter', 'partsOfSpeech': ['noun']},
    {'word': 'day', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'dead', 'partsOfSpeech': ['noun', 'noun', 'noun', 'verb', 'adjective', 'adverb']},
    {'word': 'deal', 'partsOfSpeech': ['noun']},
    {'word': 'death', 'partsOfSpeech': ['noun']},
    {'word': 'debate', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'decade', 'partsOfSpeech': ['noun']},
    {'word': 'decide', 'partsOfSpeech': ['verb']},
    {'word': 'decision', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'deep', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'defense', 'partsOfSpeech': ['noun']},
    {'word': 'degree', 'partsOfSpeech': ['noun']},
    {'word': 'democrat', 'partsOfSpeech': ['noun']},
    {'word': 'democratic', 'partsOfSpeech': ['adjective']},
    {'word': 'describe', 'partsOfSpeech': ['verb']},
    {'word': 'design', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'despite', 'partsOfSpeech': ['noun', 'verb', 'preposition']},
    {'word': 'detail', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'determine', 'partsOfSpeech': ['verb']},
    {'word': 'develop', 'partsOfSpeech': ['verb']},
    {'word': 'development', 'partsOfSpeech': ['noun']},
    {'word': 'die', 'partsOfSpeech': ['verb']},
    {'word': 'difference', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'different', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'difficult', 'partsOfSpeech': ['verb', 'adjective']},
    {'word': 'dinner', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'direction', 'partsOfSpeech': ['noun']},
    {'word': 'director', 'partsOfSpeech': ['noun']},
    {'word': 'discover', 'partsOfSpeech': ['verb']},
    {'word': 'discuss', 'partsOfSpeech': ['verb']},
    {'word': 'discussion', 'partsOfSpeech': ['noun']},
    {'word': 'disease', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'do', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'doctor', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'dog', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'door', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'down', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'preposition']},
    {'word': 'draw', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'dream', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'drive', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'drop', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'drug', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'during', 'partsOfSpeech': ['verb', 'preposition']},
    {'word': 'each', 'partsOfSpeech': ['noun', 'adverb', 'pronoun']},
    {'word': 'early', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'east', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'easy', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'verb']},
    {'word': 'eat', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'economic', 'partsOfSpeech': ['adjective']},
    {'word': 'economy', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'edge', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'education', 'partsOfSpeech': ['noun']},
    {'word': 'effect', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'effort', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'eight', 'partsOfSpeech': ['noun', 'numeral', 'adjective']},
    {'word': 'either', 'partsOfSpeech': ['adverb', 'pronoun', 'conjunction']},
    {'word': 'election', 'partsOfSpeech': ['noun']},
    {'word': 'else', 'partsOfSpeech': ['adjective', 'adverb', 'conjunction']},
    {'word': 'employee', 'partsOfSpeech': ['noun']},
    {'word': 'end', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'energy', 'partsOfSpeech': ['noun']},
    {'word': 'enjoy', 'partsOfSpeech': ['verb']},
    {'word': 'enough', 'partsOfSpeech': ['adverb', 'pronoun', 'interjection']},
    {'word': 'enter', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'entire', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'environment', 'partsOfSpeech': ['noun']},
    {'word': 'environmental', 'partsOfSpeech': ['adjective']},
    {'word': 'especially', 'partsOfSpeech': ['adverb']},
    {'word': 'establish', 'partsOfSpeech': ['verb']},
    {'word': 'even', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'evening', 'partsOfSpeech': ['noun']},
    {'word': 'event', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'ever', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'everybody', 'partsOfSpeech': ['pronoun']},
    {'word': 'everyone', 'partsOfSpeech': ['pronoun']},
    {'word': 'everything', 'partsOfSpeech': ['pronoun']},
    {'word': 'evidence', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'exactly', 'partsOfSpeech': ['adverb', 'interjection']},
    {'word': 'example', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'executive', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'exist', 'partsOfSpeech': ['verb']},
    {'word': 'expect', 'partsOfSpeech': ['verb']},
    {'word': 'experience', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'expert', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'explain', 'partsOfSpeech': ['verb']},
    {'word': 'eye', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'face', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'fact', 'partsOfSpeech': ['noun', 'interjection']},
    {'word': 'factor', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'fail', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'fall', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'family', 'partsOfSpeech': ['noun', 'adjective', 'noun']},
    {'word': 'far', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'fast', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'interjection']},
    {'word': 'father', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'fear', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'federal', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'feel', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'feeling', 'partsOfSpeech': ['verb', 'noun', 'adjective']},
    {'word': 'few', 'partsOfSpeech': ['pronoun']},
    {'word': 'field', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'fight', 'partsOfSpeech': ['verb']},
    {'word': 'figure', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'fill', 'partsOfSpeech': ['verb']},
    {'word': 'film', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'final', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'finally', 'partsOfSpeech': ['adverb']},
    {'word': 'financial', 'partsOfSpeech': ['adjective']},
    {'word': 'find', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'fine', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'finger', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'finish', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'fire', 'partsOfSpeech': ['noun']},
    {'word': 'firm', 'partsOfSpeech': ['noun']},
    {'word': 'first', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'fish', 'partsOfSpeech': ['noun']},
    {'word': 'five', 'partsOfSpeech': ['noun', 'numeral']},
    {'word': 'floor', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'fly', 'partsOfSpeech': ['noun']},
    {'word': 'focus', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'follow', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'food', 'partsOfSpeech': ['noun']},
    {'word': 'foot', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'force', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'foreign', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'forget', 'partsOfSpeech': ['verb']},
    {'word': 'form', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'former', 'partsOfSpeech': ['adjective']},
    {'word': 'forward', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'four', 'partsOfSpeech': ['noun', 'numeral']},
    {'word': 'free', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'noun']},
    {'word': 'friend', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'from', 'partsOfSpeech': ['preposition']},
    {'word': 'front', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'full', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'fund', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'future', 'partsOfSpeech': ['noun', 'adjective', 'noun']},
    {'word': 'game', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'garden', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'gas', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'general', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'generation', 'partsOfSpeech': ['noun']},
    {'word': 'get', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'girl', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'give', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'glass', 'partsOfSpeech': ['verb', 'noun', 'verb']},
    {'word': 'go', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'goal', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'good', 'partsOfSpeech': ['adjective', 'interjection']},
    {'word': 'government', 'partsOfSpeech': ['noun']},
    {'word': 'great', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'interjection']},
    {'word': 'green', 'partsOfSpeech': ['adjective']},
    {'word': 'ground', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'group', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'grow', 'partsOfSpeech': ['verb']},
    {'word': 'growth', 'partsOfSpeech': ['noun']},
    {'word': 'guess', 'partsOfSpeech': ['verb']},
    {'word': 'gun', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'guy', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'hair', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'half', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'preposition']},
    {'word': 'hand', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'hang', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'happen', 'partsOfSpeech': ['verb', 'adverb']},
    {'word': 'happy', 'partsOfSpeech': ['noun', 'noun', 'verb', 'adjective']},
    {'word': 'hard', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'have', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'he', 'partsOfSpeech': ['noun', 'pronoun']},
    {'word': 'head', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'health', 'partsOfSpeech': ['noun']},
    {'word': 'hear', 'partsOfSpeech': ['verb']},
    {'word': 'heart', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'heat', 'partsOfSpeech': ['noun']},
    {'word': 'heavy', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'help', 'partsOfSpeech': ['noun']},
    {'word': 'her', 'partsOfSpeech': ['noun', 'pronoun']},
    {'word': 'here', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'interjection']},
    {'word': 'herself', 'partsOfSpeech': ['pronoun']},
    {'word': 'high', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'him', 'partsOfSpeech': ['pronoun', 'noun', 'pronoun']},
    {'word': 'himself', 'partsOfSpeech': ['pronoun']},
    {'word': 'his', 'partsOfSpeech': ['pronoun', 'pronoun']},
    {'word': 'history', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'hit', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'hold', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'home', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'noun']},
    {'word': 'hope', 'partsOfSpeech': ['verb']},
    {'word': 'hospital', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'hot', 'partsOfSpeech': ['verb', 'adjective']},
    {'word': 'hotel', 'partsOfSpeech': ['noun']},
    {'word': 'hour', 'partsOfSpeech': ['noun']},
    {'word': 'house', 'partsOfSpeech': ['noun']},
    {'word': 'how', 'partsOfSpeech': ['noun', 'adverb', 'conjunction']},
    {'word': 'however', 'partsOfSpeech': ['adverb', 'conjunction']},
    {'word': 'huge', 'partsOfSpeech': ['adjective']},
    {'word': 'human', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'hundred', 'partsOfSpeech': ['noun', 'numeral']},
    {'word': 'husband', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'i', 'partsOfSpeech': ['noun']},
    {'word': 'idea', 'partsOfSpeech': ['noun']},
    {'word': 'identify', 'partsOfSpeech': ['verb']},
    {'word': 'if', 'partsOfSpeech': ['noun', 'conjunction']},
    {'word': 'image', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'imagine', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'impact', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'important', 'partsOfSpeech': ['adjective']},
    {'word': 'improve', 'partsOfSpeech': ['verb']},
    {'word': 'in', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'preposition']},
    {'word': 'include', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'including', 'partsOfSpeech': ['verb', 'preposition']},
    {'word': 'increase', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'indeed', 'partsOfSpeech': ['adverb', 'interjection']},
    {'word': 'indicate', 'partsOfSpeech': ['verb']},
    {'word': 'individual', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'industry', 'partsOfSpeech': ['noun']},
    {'word': 'information', 'partsOfSpeech': ['noun']},
    {'word': 'inside', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'preposition']},
    {'word': 'instead', 'partsOfSpeech': ['adverb']},
    {'word': 'institution', 'partsOfSpeech': ['noun']},
    {'word': 'interest', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'interesting', 'partsOfSpeech': ['verb', 'adjective']},
    {'word': 'international', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'interview', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'into', 'partsOfSpeech': ['preposition']},
    {'word': 'investment', 'partsOfSpeech': ['noun']},
    {'word': 'involve', 'partsOfSpeech': ['verb']},
    {'word': 'issue', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'it', 'partsOfSpeech': ['noun', 'adjective', 'pronoun']},
    {'word': 'item', 'partsOfSpeech': ['noun', 'verb', 'adverb']},
    {'word': 'its', 'partsOfSpeech': ['noun', 'pronoun']},
    {'word': 'itself', 'partsOfSpeech': ['pronoun']},
    {'word': 'job', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'join', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'just', 'partsOfSpeech': ['adjective', 'adverb', 'interjection']},
    {'word': 'keep', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'key', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'kid', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'kill', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'kind', 'partsOfSpeech': ['noun']},
    {'word': 'kitchen', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'know', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'knowledge', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'land', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'language', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'large', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'last', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'late', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'later', 'partsOfSpeech': ['adjective', 'adverb', 'adverb', 'interjection']},
    {'word': 'laugh', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'law', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'lawyer', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'lay', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'lead', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'leader', 'partsOfSpeech': ['noun']},
    {'word': 'learn', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'least', 'partsOfSpeech': ['noun', 'adverb']},
    {'word': 'leave', 'partsOfSpeech': ['verb']},
    {'word': 'left', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'leg', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'legal', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'less', 'partsOfSpeech': ['noun', 'verb', 'adverb', 'preposition']},
    {'word': 'let', 'partsOfSpeech': ['noun', 'verb', 'verb']},
    {'word': 'letter', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'level', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'lie', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'life', 'partsOfSpeech': ['noun']},
    {'word': 'light', 'partsOfSpeech': ['noun']},
    {'word': 'like', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'likely', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'line', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'list', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'listen', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'little', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'pronoun']},
    {'word': 'live', 'partsOfSpeech': ['verb']},
    {'word': 'local', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'noun']},
    {'word': 'long', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'lose', 'partsOfSpeech': ['verb']},
    {'word': 'loss', 'partsOfSpeech': ['noun']},
    {'word': 'lot', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'love', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'low', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'machine', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'magazine', 'partsOfSpeech': ['noun']},
    {'word': 'main', 'partsOfSpeech': ['verb', 'adjective', 'adverb']},
    {'word': 'maintain', 'partsOfSpeech': ['verb']},
    {'word': 'major', 'partsOfSpeech': ['noun']},
    {'word': 'majority', 'partsOfSpeech': ['noun']},
    {'word': 'make', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'man', 'partsOfSpeech': ['noun', 'interjection']},
    {'word': 'manage', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'management', 'partsOfSpeech': ['noun']},
    {'word': 'manager', 'partsOfSpeech': ['noun']},
    {'word': 'many', 'partsOfSpeech': ['noun', 'adjective', 'pronoun']},
    {'word': 'market', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'marriage', 'partsOfSpeech': ['noun']},
    {'word': 'material', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'matter', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'may', 'partsOfSpeech': ['verb']},
    {'word': 'maybe', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'me', 'partsOfSpeech': ['pronoun']},
    {'word': 'mean', 'partsOfSpeech': ['verb', 'verb']},
    {'word': 'measure', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'media', 'partsOfSpeech': ['noun']},
    {'word': 'medical', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'meet', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'meeting', 'partsOfSpeech': ['noun']},
    {'word': 'member', 'partsOfSpeech': ['noun']},
    {'word': 'memory', 'partsOfSpeech': ['noun']},
    {'word': 'mention', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'message', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'method', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'middle', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'might', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'military', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'million', 'partsOfSpeech': ['numeral']},
    {'word': 'mind', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'minute', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'miss', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'mission', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'model', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'modern', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'moment', 'partsOfSpeech': ['noun']},
    {'word': 'money', 'partsOfSpeech': ['noun']},
    {'word': 'month', 'partsOfSpeech': ['noun']},
    {'word': 'more', 'partsOfSpeech': ['adverb', 'pronoun']},
    {'word': 'morning', 'partsOfSpeech': ['noun', 'interjection']},
    {'word': 'most', 'partsOfSpeech': ['noun', 'adverb', 'pronoun']},
    {'word': 'mother', 'partsOfSpeech': ['noun']},
    {'word': 'mouth', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'move', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'movement', 'partsOfSpeech': ['noun']},
    {'word': 'movie', 'partsOfSpeech': ['noun']},
    {'word': 'much', 'partsOfSpeech': ['adjective', 'adverb', 'pronoun']},
    {'word': 'music', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'must', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'my', 'partsOfSpeech': ['interjection']},
    {'word': 'myself', 'partsOfSpeech': ['pronoun']},
    {'word': 'name', 'partsOfSpeech': ['noun']},
    {'word': 'nation', 'partsOfSpeech': ['noun']},
    {'word': 'national', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'natural', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'nature', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'near', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'preposition']},
    {'word': 'nearly', 'partsOfSpeech': ['adverb']},
    {'word': 'necessary', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'need', 'partsOfSpeech': ['noun']},
    {'word': 'network', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'never', 'partsOfSpeech': ['adverb']},
    {'word': 'new', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'verb']},
    {'word': 'news', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'newspaper', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'next', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'preposition']},
    {'word': 'nice', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'interjection']},
    {'word': 'night', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'no', 'partsOfSpeech': ['noun', 'adverb', 'preposition']},
    {'word': 'none', 'partsOfSpeech': ['noun', 'adverb', 'pronoun']},
    {'word': 'nor', 'partsOfSpeech': ['conjunction']},
    {'word': 'north', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'not', 'partsOfSpeech': ['noun', 'adverb', 'conjunction', 'interjection']},
    {'word': 'note', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'nothing', 'partsOfSpeech': ['noun', 'adverb', 'pronoun']},
    {'word': 'notice', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'now', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'conjunction', 'interjection']},
    {'word': 'number', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'occur', 'partsOfSpeech': ['verb']},
    {'word': 'of', 'partsOfSpeech': ['preposition']},
    {'word': 'off', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'preposition']},
    {'word': 'offer', 'partsOfSpeech': ['noun']},
    {'word': 'office', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'officer', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'official', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'often', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'oh', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'oil', 'partsOfSpeech': ['noun']},
    {'word': 'ok', 'partsOfSpeech': ['adjective']},
    {'word': 'old', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'on', 'partsOfSpeech': ['verb', 'adjective', 'adverb', 'preposition']},
    {'word': 'once', 'partsOfSpeech': ['adverb', 'conjunction']},
    {'word': 'one', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'numeral', 'pronoun']},
    {'word': 'only', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'conjunction']},
    {'word': 'onto', 'partsOfSpeech': ['adjective', 'preposition']},
    {'word': 'open', 'partsOfSpeech': ['adjective']},
    {'word': 'operation', 'partsOfSpeech': ['noun']},
    {'word': 'opportunity', 'partsOfSpeech': ['noun']},
    {'word': 'option', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'or', 'partsOfSpeech': ['conjunction']},
    {'word': 'order', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'organization', 'partsOfSpeech': ['noun']},
    {'word': 'other', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'others', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'out', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'preposition', 'interjection']},
    {'word': 'outside', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'preposition']},
    {'word': 'over', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'preposition', 'interjection']},
    {'word': 'own', 'partsOfSpeech': ['adjective']},
    {'word': 'owner', 'partsOfSpeech': ['noun']},
    {'word': 'page', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'pain', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'painting', 'partsOfSpeech': ['verb', 'noun']},
    {'word': 'paper', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'parent', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'part', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'participant', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'particular', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'particularly', 'partsOfSpeech': ['adverb']},
    {'word': 'partner', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'party', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'pass', 'partsOfSpeech': ['verb']},
    {'word': 'past', 'partsOfSpeech': ['verb', 'noun', 'adjective', 'adverb', 'preposition']},
    {'word': 'patient', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'pattern', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'pay', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'peace', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'people', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'per', 'partsOfSpeech': ['preposition']},
    {'word': 'perform', 'partsOfSpeech': ['verb']},
    {'word': 'performance', 'partsOfSpeech': ['noun']},
    {'word': 'perhaps', 'partsOfSpeech': ['noun', 'adverb']},
    {'word': 'period', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'interjection']},
    {'word': 'person', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'personal', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'phone', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'physical', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'pick', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'picture', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'piece', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'place', 'partsOfSpeech': ['noun']},
    {'word': 'plan', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'plant', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'play', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'player', 'partsOfSpeech': ['noun']},
    {'word': 'pm', 'partsOfSpeech': ['adverb', 'adverb']},
    {'word': 'point', 'partsOfSpeech': ['noun']},
    {'word': 'police', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'policy', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'political', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'politics', 'partsOfSpeech': ['verb', 'noun']},
    {'word': 'poor', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'popular', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'population', 'partsOfSpeech': ['noun']},
    {'word': 'position', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'positive', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'possible', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'power', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'practice', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'prepare', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'present', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'president', 'partsOfSpeech': ['noun', 'noun', 'adjective']},
    {'word': 'pressure', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'pretty', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'prevent', 'partsOfSpeech': ['verb']},
    {'word': 'price', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'private', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'probably', 'partsOfSpeech': ['adverb']},
    {'word': 'problem', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'process', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'produce', 'partsOfSpeech': ['verb']},
    {'word': 'product', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'production', 'partsOfSpeech': ['noun']},
    {'word': 'professional', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'professor', 'partsOfSpeech': ['noun']},
    {'word': 'program', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'project', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'property', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'protect', 'partsOfSpeech': ['verb']},
    {'word': 'prove', 'partsOfSpeech': ['verb', 'noun', 'verb']},
    {'word': 'provide', 'partsOfSpeech': ['verb']},
    {'word': 'public', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'pull', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'purpose', 'partsOfSpeech': ['noun']},
    {'word': 'push', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'put', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'quality', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'question', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'quickly', 'partsOfSpeech': ['adverb']},
    {'word': 'quite', 'partsOfSpeech': ['adverb', 'interjection']},
    {'word': 'race', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'radio', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'raise', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'range', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'rate', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'rather', 'partsOfSpeech': ['verb', 'adjective', 'adverb', 'interjection']},
    {'word': 'reach', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'read', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'ready', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'real', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'reality', 'partsOfSpeech': ['noun']},
    {'word': 'realize', 'partsOfSpeech': ['verb']},
    {'word': 'really', 'partsOfSpeech': ['adverb', 'interjection']},
    {'word': 'reason', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'receive', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'recent', 'partsOfSpeech': ['adjective']},
    {'word': 'recently', 'partsOfSpeech': ['adverb']},
    {'word': 'recognize', 'partsOfSpeech': ['verb']},
    {'word': 'record', 'partsOfSpeech': ['noun', 'noun']},
    {'word': 'red', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'reduce', 'partsOfSpeech': ['verb']},
    {'word': 'reflect', 'partsOfSpeech': ['verb']},
    {'word': 'region', 'partsOfSpeech': ['noun']},
    {'word': 'relate', 'partsOfSpeech': ['verb']},
    {'word': 'relationship', 'partsOfSpeech': ['noun']},
    {'word': 'religious', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'remain', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'remember', 'partsOfSpeech': ['verb']},
    {'word': 'remove', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'report', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'represent', 'partsOfSpeech': ['verb']},
    {'word': 'republican', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'require', 'partsOfSpeech': ['verb']},
    {'word': 'research', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'resource', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'respond', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'response', 'partsOfSpeech': ['noun']},
    {'word': 'responsibility', 'partsOfSpeech': ['noun']},
    {'word': 'rest', 'partsOfSpeech': ['noun']},
    {'word': 'result', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'return', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'reveal', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'rich', 'partsOfSpeech': ['verb', 'adjective']},
    {'word': 'right', 'partsOfSpeech': ['adjective']},
    {'word': 'rise', 'partsOfSpeech': ['verb']},
    {'word': 'risk', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'road', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'rock', 'partsOfSpeech': ['noun']},
    {'word': 'role', 'partsOfSpeech': ['noun']},
    {'word': 'room', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'rule', 'partsOfSpeech': ['noun']},
    {'word': 'run', 'partsOfSpeech': ['verb', 'noun', 'verb', 'adjective']},
    {'word': 'safe', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'same', 'partsOfSpeech': ['adjective', 'pronoun', 'interjection']},
    {'word': 'save', 'partsOfSpeech': ['noun', 'verb', 'preposition', 'conjunction']},
    {'word': 'say', 'partsOfSpeech': ['noun', 'verb', 'adverb', 'interjection']},
    {'word': 'scene', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'school', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'science', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'scientist', 'partsOfSpeech': ['noun']},
    {'word': 'score', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'sea', 'partsOfSpeech': ['noun']},
    {'word': 'season', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'seat', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'second', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'section', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'security', 'partsOfSpeech': ['noun']},
    {'word': 'see', 'partsOfSpeech': ['verb', 'interjection']},
    {'word': 'seek', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'seem', 'partsOfSpeech': ['verb']},
    {'word': 'sell', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'send', 'partsOfSpeech': ['noun', 'noun', 'verb']},
    {'word': 'senior', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'sense', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'series', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'serious', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'serve', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'service', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'set', 'partsOfSpeech': ['verb']},
    {'word': 'seven', 'partsOfSpeech': ['noun', 'numeral']},
    {'word': 'several', 'partsOfSpeech': ['noun', 'adverb']},
    {'word': 'sex', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'sexual', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'shake', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'share', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'she', 'partsOfSpeech': ['noun', 'pronoun']},
    {'word': 'shoot', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'short', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'preposition']},
    {'word': 'shot', 'partsOfSpeech': ['verb', 'noun', 'verb', 'adjective']},
    {'word': 'should', 'partsOfSpeech': ['verb', 'noun', 'verb', 'verb']},
    {'word': 'shoulder', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'show', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'side', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'sign', 'partsOfSpeech': ['noun']},
    {'word': 'significant', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'similar', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'simple', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'simply', 'partsOfSpeech': ['adverb']},
    {'word': 'since', 'partsOfSpeech': ['adverb', 'preposition', 'conjunction']},
    {'word': 'sing', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'single', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'sister', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'sit', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'site', 'partsOfSpeech': ['noun']},
    {'word': 'situation', 'partsOfSpeech': ['noun']},
    {'word': 'six', 'partsOfSpeech': ['noun', 'numeral']},
    {'word': 'size', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'skill', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'skin', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'small', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'smile', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'so', 'partsOfSpeech': ['adjective', 'adverb', 'conjunction', 'interjection']},
    {'word': 'social', 'partsOfSpeech': ['noun', 'adjective', 'noun', 'noun', 'noun', 'noun']},
    {'word': 'society', 'partsOfSpeech': ['noun']},
    {'word': 'soldier', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'some', 'partsOfSpeech': ['adverb', 'pronoun']},
    {'word': 'somebody', 'partsOfSpeech': ['noun', 'pronoun']},
    {'word': 'someone', 'partsOfSpeech': ['noun', 'pronoun']},
    {'word': 'something', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'pronoun']},
    {'word': 'sometimes', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'son', 'partsOfSpeech': ['noun']},
    {'word': 'song', 'partsOfSpeech': ['noun']},
    {'word': 'soon', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'sort', 'partsOfSpeech': ['noun']},
    {'word': 'sound', 'partsOfSpeech': ['adjective', 'adverb', 'interjection']},
    {'word': 'source', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'south', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'southern', 'partsOfSpeech': ['noun', 'adjective', 'noun']},
    {'word': 'space', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'speak', 'partsOfSpeech': ['noun', 'noun', 'verb']},
    {'word': 'special', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'specific', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'speech', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'spend', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'sport', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'spring', 'partsOfSpeech': ['verb', 'noun', 'verb', 'verb', 'verb']},
    {'word': 'staff', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'stage', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'stand', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'standard', 'partsOfSpeech': ['noun', 'adjective', 'interjection']},
    {'word': 'star', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'start', 'partsOfSpeech': ['noun']},
    {'word': 'state', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'statement', 'partsOfSpeech': ['noun']},
    {'word': 'station', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'stay', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'step', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'still', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'stock', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'stop', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'store', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'story', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'strategy', 'partsOfSpeech': ['noun']},
    {'word': 'street', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'strong', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'structure', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'student', 'partsOfSpeech': ['noun']},
    {'word': 'study', 'partsOfSpeech': ['verb']},
    {'word': 'stuff', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'style', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'subject', 'partsOfSpeech': ['adjective']},
    {'word': 'success', 'partsOfSpeech': ['noun']},
    {'word': 'successful', 'partsOfSpeech': ['adjective']},
    {'word': 'such', 'partsOfSpeech': ['noun', 'pronoun']},
    {'word': 'suddenly', 'partsOfSpeech': ['adverb']},
    {'word': 'suffer', 'partsOfSpeech': ['verb']},
    {'word': 'suggest', 'partsOfSpeech': ['verb']},
    {'word': 'summer', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'support', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'sure', 'partsOfSpeech': ['adjective', 'adverb', 'interjection']},
    {'word': 'surface', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'system', 'partsOfSpeech': ['noun']},
    {'word': 'table', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'take', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'talk', 'partsOfSpeech': ['verb']},
    {'word': 'task', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'tax', 'partsOfSpeech': ['noun']},
    {'word': 'teach', 'partsOfSpeech': ['verb']},
    {'word': 'teacher', 'partsOfSpeech': ['noun']},
    {'word': 'team', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'technology', 'partsOfSpeech': ['noun']},
    {'word': 'television', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'tell', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'ten', 'partsOfSpeech': ['noun', 'numeral']},
    {'word': 'tend', 'partsOfSpeech': ['verb']},
    {'word': 'term', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'test', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'than', 'partsOfSpeech': ['adverb', 'preposition', 'conjunction']},
    {'word': 'thank', 'partsOfSpeech': ['noun']},
    {'word': 'that', 'partsOfSpeech': ['noun', 'adverb', 'pronoun', 'conjunction']},
    {'word': 'the', 'partsOfSpeech': ['adverb']},
    {'word': 'them', 'partsOfSpeech': ['pronoun']},
    {'word': 'themselves', 'partsOfSpeech': ['pronoun']},
    {'word': 'then', 'partsOfSpeech': ['conjunction', 'noun', 'adjective', 'adverb']},
    {'word': 'theory', 'partsOfSpeech': ['noun']},
    {'word': 'there', 'partsOfSpeech': ['noun', 'adverb', 'pronoun', 'interjection']},
    {'word': 'these', 'partsOfSpeech': ['pronoun']},
    {'word': 'they', 'partsOfSpeech': ['pronoun']},
    {'word': 'thing', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'think', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'third', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'this', 'partsOfSpeech': ['noun', 'adverb', 'pronoun', 'interjection']},
    {'word': 'those', 'partsOfSpeech': ['pronoun']},
    {'word': 'though', 'partsOfSpeech': ['adverb', 'conjunction']},
    {'word': 'thought', 'partsOfSpeech': ['verb', 'verb', 'noun']},
    {'word': 'thousand', 'partsOfSpeech': ['numeral']},
    {'word': 'threat', 'partsOfSpeech': ['noun']},
    {'word': 'three', 'partsOfSpeech': ['noun', 'numeral', 'noun']},
    {'word': 'through', 'partsOfSpeech': ['noun', 'adjective', 'adverb', 'preposition']},
    {'word': 'throughout', 'partsOfSpeech': ['adverb', 'preposition']},
    {'word': 'throw', 'partsOfSpeech': ['verb', 'noun', 'verb']},
    {'word': 'thus', 'partsOfSpeech': ['adverb']},
    {'word': 'time', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'to', 'partsOfSpeech': ['adverb', 'preposition']},
    {'word': 'today', 'partsOfSpeech': ['noun', 'adverb']},
    {'word': 'together', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'tonight', 'partsOfSpeech': ['noun', 'adverb']},
    {'word': 'too', 'partsOfSpeech': ['adverb']},
    {'word': 'top', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'total', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'tough', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'interjection']},
    {'word': 'toward', 'partsOfSpeech': ['adjective', 'preposition']},
    {'word': 'town', 'partsOfSpeech': ['noun']},
    {'word': 'trade', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'traditional', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'training', 'partsOfSpeech': ['verb', 'noun']},
    {'word': 'travel', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'treat', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'treatment', 'partsOfSpeech': ['noun']},
    {'word': 'tree', 'partsOfSpeech': ['noun', 'noun', 'verb']},
    {'word': 'trial', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'trip', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'trouble', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'true', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'truth', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'try', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'turn', 'partsOfSpeech': ['verb']},
    {'word': 'tv', 'partsOfSpeech': ['noun', 'noun', 'noun', 'noun']},
    {'word': 'two', 'partsOfSpeech': ['noun', 'numeral']},
    {'word': 'type', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'under', 'partsOfSpeech': ['adjective', 'adverb', 'preposition']},
    {'word': 'understand', 'partsOfSpeech': ['verb']},
    {'word': 'unit', 'partsOfSpeech': ['noun', 'noun', 'adjective']},
    {'word': 'until', 'partsOfSpeech': ['preposition', 'conjunction']},
    {'word': 'up', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb', 'preposition']},
    {'word': 'upon', 'partsOfSpeech': ['adverb', 'preposition']},
    {'word': 'us', 'partsOfSpeech': ['pronoun']},
    {'word': 'use', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'usually', 'partsOfSpeech': ['adverb']},
    {'word': 'value', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'various', 'partsOfSpeech': ['adjective']},
    {'word': 'very', 'partsOfSpeech': ['adjective', 'adverb']},
    {'word': 'victim', 'partsOfSpeech': ['noun']},
    {'word': 'view', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'violence', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'visit', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'voice', 'partsOfSpeech': ['noun']},
    {'word': 'vote', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'wait', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'walk', 'partsOfSpeech': ['verb']},
    {'word': 'wall', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'want', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'war', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'watch', 'partsOfSpeech': ['noun']},
    {'word': 'water', 'partsOfSpeech': ['noun']},
    {'word': 'way', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'we', 'partsOfSpeech': ['pronoun']},
    {'word': 'weapon', 'partsOfSpeech': ['noun']},
    {'word': 'wear', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'week', 'partsOfSpeech': ['noun']},
    {'word': 'weight', 'partsOfSpeech': ['noun', 'noun', 'noun', 'verb']},
    {'word': 'well', 'partsOfSpeech': ['adjective', 'adverb', 'interjection']},
    {'word': 'west', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'western', 'partsOfSpeech': ['noun', 'adjective']},
    {'word': 'what', 'partsOfSpeech': ['adverb', 'noun', 'adverb', 'pronoun', 'interjection']},
    {'word': 'whatever', 'partsOfSpeech': ['adjective', 'pronoun', 'interjection']},
    {'word': 'when', 'partsOfSpeech': ['noun', 'adverb', 'pronoun', 'conjunction', 'interjection']},
    {'word': 'where', 'partsOfSpeech': ['noun', 'adverb', 'pronoun', 'conjunction']},
    {'word': 'whether', 'partsOfSpeech': ['pronoun', 'conjunction']},
    {'word': 'which', 'partsOfSpeech': ['pronoun']},
    {'word': 'while', 'partsOfSpeech': ['noun', 'verb', 'preposition', 'conjunction']},
    {'word': 'white', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'who', 'partsOfSpeech': ['noun', 'pronoun']},
    {'word': 'whole', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'whom', 'partsOfSpeech': ['pronoun']},
    {'word': 'whose', 'partsOfSpeech': ['pronoun']},
    {'word': 'why', 'partsOfSpeech': ['noun', 'adverb', 'interjection']},
    {'word': 'wide', 'partsOfSpeech': ['noun', 'adjective', 'adverb']},
    {'word': 'wife', 'partsOfSpeech': ['noun', 'verb', 'noun']},
    {'word': 'will', 'partsOfSpeech': ['verb']},
    {'word': 'win', 'partsOfSpeech': ['verb']},
    {'word': 'wind', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'window', 'partsOfSpeech': ['noun', 'noun', 'verb']},
    {'word': 'wish', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'with', 'partsOfSpeech': ['adverb', 'preposition']},
    {'word': 'within', 'partsOfSpeech': ['adjective', 'adverb', 'preposition']},
    {'word': 'without', 'partsOfSpeech': ['adverb', 'preposition', 'conjunction']},
    {'word': 'woman', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'wonder', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'word', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'work', 'partsOfSpeech': ['noun']},
    {'word': 'worker', 'partsOfSpeech': ['noun']},
    {'word': 'world', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'worry', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'would', 'partsOfSpeech': ['noun']},
    {'word': 'write', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'writer', 'partsOfSpeech': ['noun']},
    {'word': 'wrong', 'partsOfSpeech': ['noun', 'verb', 'adjective', 'adverb']},
    {'word': 'yard', 'partsOfSpeech': ['noun', 'verb']},
    {'word': 'yeah', 'partsOfSpeech': ['interjection']},
    {'word': 'year', 'partsOfSpeech': ['noun']},
    {'word': 'yes', 'partsOfSpeech': ['noun', 'verb', 'interjection']},
    {'word': 'yet', 'partsOfSpeech': ['adverb', 'conjunction']},
    {'word': 'you', 'partsOfSpeech': ['verb', 'pronoun']},
    {'word': 'young', 'partsOfSpeech': ['noun', 'verb', 'adjective']},
    {'word': 'yourself', 'partsOfSpeech': ['pronoun']}]

SENTENCE_STRUCTURE=[['Pronoun', 'Verb', 'Noun'],
['Pronoun', 'Verb', 'Adjective', 'Noun'],
['Pronoun', 'Verb', 'Adverb', 'Adjective', 'Noun'],
['Pronoun', 'Verb', 'Preposition', 'Article', 'Noun'],
['Pronoun', 'Verb', 'Adverb', 'Noun'],
['Pronoun', 'Verb', 'Numeral', 'Noun'],
['Pronoun', 'Verb', 'Conjunction', 'Verb', 'Noun'],
['Pronoun', 'Verb', 'Interjection'],
['Pronoun', 'Verb', 'Adjective'],
['Pronoun', 'Verb', 'Preposition', 'Noun'],
['Article', 'Noun', 'Verb'],
['Article', 'Noun', 'Verb', 'Adjective'],
['Article', 'Noun', 'Verb', 'Adverb', 'Adjective'],
['Article', 'Noun', 'Verb', 'Preposition', 'Article', 'Noun'],
['Article', 'Noun', 'Verb', 'Adverb', 'Noun'],
['Article', 'Noun', 'Verb', 'Numeral', 'Noun'],
['Article', 'Noun', 'Verb', 'Conjunction', 'Verb', 'Noun'],
['Article', 'Noun', 'Verb', 'Interjection'],
['Article', 'Noun', 'Verb', 'Adjective'],
['Article', 'Noun', 'Verb', 'Preposition', 'Noun'],
['Adjective', 'Noun', 'Verb'],
['Adjective', 'Noun', 'Verb', 'Adjective'],
['Adjective', 'Noun', 'Verb', 'Adverb', 'Adjective'],
['Adjective', 'Noun', 'Verb', 'Preposition', 'Article', 'Noun'],
['Adjective', 'Noun', 'Verb', 'Adverb', 'Noun'],
['Adjective', 'Noun', 'Verb', 'Numeral', 'Noun'],
['Adjective', 'Noun', 'Verb', 'Conjunction', 'Verb', 'Noun'],
['Adjective', 'Noun', 'Verb', 'Interjection'],
['Adjective', 'Noun', 'Verb', 'Adjective'],
['Adjective', 'Noun', 'Verb', 'Preposition', 'Noun'],
['Noun', 'Verb'],
['Noun', 'Verb', 'Adjective'],
['Noun', 'Verb', 'Adverb', 'Adjective'],
['Noun', 'Verb', 'Preposition', 'Article', 'Noun'],
['Noun', 'Verb', 'Adverb', 'Noun'],
['Noun', 'Verb', 'Numeral', 'Noun'],
['Noun', 'Verb', 'Conjunction', 'Verb', 'Noun'],
['Noun', 'Verb', 'Interjection'],
['Noun', 'Verb', 'Adjective'],
['Noun', 'Verb', 'Preposition', 'Noun'],
['Adverb', 'Adjective', 'Noun', 'Verb'],
['Adverb', 'Adjective', 'Noun', 'Verb', 'Adjective'],
['Adverb', 'Adjective', 'Noun', 'Verb', 'Adverb', 'Adjective'],
['Adverb', 'Adjective', 'Noun', 'Verb', 'Preposition', 'Article', 'Noun'],
['Adverb', 'Adjective', 'Noun', 'Verb', 'Adverb', 'Noun'],
['Adverb', 'Adjective', 'Noun', 'Verb', 'Numeral', 'Noun'],
['Adverb', 'Adjective', 'Noun', 'Verb', 'Conjunction', 'Verb', 'Noun'],
['Adverb', 'Adjective', 'Noun', 'Verb', 'Interjection'],
['Adverb', 'Adjective', 'Noun', 'Verb', 'Adjective'],
['Adverb', 'Adjective', 'Noun', 'Verb', 'Preposition', 'Noun'],
['Preposition', 'Article', 'Noun', 'Verb'],
['Preposition', 'Article', 'Noun', 'Verb', 'Adjective'],
['Preposition', 'Article', 'Noun', 'Verb', 'Adverb', 'Adjective'],
['Preposition', 'Article', 'Noun', 'Verb', 'Preposition', 'Article', 'Noun'],
['Preposition', 'Article', 'Noun', 'Verb', 'Adverb', 'Noun'],
['Preposition', 'Article', 'Noun', 'Verb', 'Numeral', 'Noun'],
['Preposition', 'Article', 'Noun', 'Verb', 'Conjunction', 'Verb', 'Noun'],
['Preposition', 'Article', 'Noun', 'Verb', 'Interjection'],
['Preposition', 'Article', 'Noun', 'Verb', 'Adjective'],
['Preposition', 'Article', 'Noun', 'Verb', 'Preposition', 'Noun'],
['Adverb', 'Noun', 'Verb'],
['Adverb', 'Noun', 'Verb', 'Adjective'],
['Adverb', 'Noun', 'Verb', 'Adverb', 'Adjective'],
['Adverb', 'Noun', 'Verb', 'Preposition', 'Article', 'Noun'],
['Adverb', 'Noun', 'Verb', 'Adverb', 'Noun'],
['Adverb', 'Noun', 'Verb', 'Numeral', 'Noun'],
['Adverb', 'Noun', 'Verb', 'Conjunction', 'Verb', 'Noun'],
['Adverb', 'Noun', 'Verb', 'Interjection'],
['Adverb', 'Noun', 'Verb', 'Adjective'],
['Adverb', 'Noun', 'Verb', 'Preposition', 'Noun'],
['Numeral', 'Noun', 'Verb'],
['Numeral', 'Noun', 'Verb', 'Adjective'],
['Numeral', 'Noun', 'Verb', 'Adverb', 'Adjective'],
['Numeral', 'Noun', 'Verb', 'Preposition', 'Article', 'Noun'],
['Numeral', 'Noun', 'Verb', 'Adverb', 'Noun'],
['Numeral', 'Noun', 'Verb', 'Numeral', 'Noun'],
['Numeral', 'Noun', 'Verb', 'Conjunction', 'Verb', 'Noun'],
['Numeral', 'Noun', 'Verb', 'Interjection'],
['Numeral', 'Noun', 'Verb', 'Adjective'],
['Numeral', 'Noun', 'Verb', 'Preposition', 'Noun'],
['Interjection', 'Verb'],
['Interjection', 'Verb', 'Adjective'],
['Interjection', 'Verb', 'Adverb', 'Adjective'],
['Interjection', 'Verb', 'Preposition', 'Article', 'Noun'],
['Interjection', 'Verb', 'Adverb', 'Noun'],
['Interjection', 'Verb', 'Numeral', 'Noun'],
['Interjection', 'Verb', 'Conjunction', 'Verb', 'Noun'],
['Interjection', 'Verb', 'Interjection'],
['Interjection', 'Verb', 'Adjective'],
['Interjection', 'Verb', 'Preposition', 'Noun'],
['Conjunction', 'Verb', 'Noun'],
['Conjunction', 'Verb', 'Noun', 'Adjective'],
['Conjunction', 'Verb', 'Noun', 'Adverb', 'Adjective'],
['Conjunction', 'Verb', 'Noun', 'Preposition', 'Article', 'Noun'],
['Conjunction', 'Verb', 'Noun', 'Adverb', 'Noun'],
['Conjunction', 'Verb', 'Noun', 'Numeral', 'Noun'],
['Conjunction', 'Verb', 'Noun', 'Conjunction', 'Verb', 'Noun'],
['Conjunction', 'Verb', 'Noun', 'Interjection'],
['Conjunction', 'Verb', 'Noun', 'Adjective'],
['Conjunction', 'Verb', 'Noun', 'Preposition', 'Noun']]

WORDS_BY_POS = {
'ARTICLE':
['a', 'an', 'the'],

'NOUN':
['ability', 'above', 'account', 'across', 'act', 'action', 'activity', 'add', 'address', 'administration', 'adult', 'age', 'agency', 'agent', 'agreement', 'air', 'all', 'almost', 'amount', 'analysis', 'and', 'animal', 'answer', 'anything', 'approach', 'area', 'arm', 'art', 'article', 'artist', 'ask', 'at', 'attack', 'attention', 'attorney', 'audience', 'author', 'authority', 'baby', 'back', 'bad', 'bag', 'ball', 'bank', 'bar', 'base', 'base', 'base', 'beat', 'beautiful', 'bed', 'begin', 'behavior', 'behind', 'benefit', 'best', 'better', 'between', 'beyond', 'big', 'bill', 'billion', 'bit', 'black', 'blood', 'blood', 'blue', 'board', 'body', 'book', 'box', 'boy', 'break', 'brother', 'budget', 'build', 'building', 'business', 'but', 'buy', 'by', 'by', 'by', 'by', 'by', 'by', 'call', 'camera', 'campaign', 'cancer', 'candidate', 'capital', 'car', 'card', 'care', 'career', 'carry', 'case', 'catch', 'cause', 'cell', 'center', 'century', 'certain', 'chair', 'chair', 'chair', 'challenge', 'chance', 'change', 'character', 'charge', 'check', 'child', 'child', 'choice', 'church', 'citizen', 'city', 'claim', 'class', 'clear', 'close', 'coach', 'collection', 'college', 'color', 'come', 'commercial', 'common', 'community', 'company', 'compare', 'computer', 'concern', 'condition', 'conference', 'congress', 'consumer', 'continue', 'control', 'could', 'country', 'country', 'couple', 'course', 'court', 'cover', 'crime', 'culture', 'cup', 'current', 'customer', 'cut', 'data', 'daughter', 'day', 'dead', 'dead', 'dead', 'deal', 'death', 'debate', 'decade', 'decision', 'deep', 'defense', 'degree', 'democrat', 'design', 'despite', 'detail', 'development', 'difference', 'different', 'dinner', 'direction', 'director', 'discussion', 'disease', 'do', 'doctor', 'dog', 'dog', 'door', 'down', 'draw', 'dream', 'drive', 'drop', 'drug', 'each', 'early', 'east', 'easy', 'eat', 'economy', 'edge', 'education', 'effect', 'effort', 'eight', 'election', 'employee', 'end', 'energy', 'enter', 'entire', 'environment', 'even', 'evening', 'event', 'evidence', 'example', 'executive', 'experience', 'expert', 'eye', 'face', 'fact', 'factor', 'fail', 'fall', 'family', 'family', 'fast', 'father', 'fear', 'federal', 'feel', 'feeling', 'field', 'figure', 'film', 'final', 'find', 'fine', 'finger', 'finish', 'fire', 'firm', 'first', 'fish', 'five', 'floor', 'fly', 'focus', 'follow', 'food', 'foot', 'force', 'force', 'foreign', 'form', 'forward', 'four', 'free', 'free', 'friend', 'front', 'fund', 'future', 'future', 'game', 'garden', 'gas', 'general', 'generation', 'get', 'girl', 'give', 'glass', 'go', 'goal', 'government', 'great', 'ground', 'group', 'growth', 'gun', 'guy', 'hair', 'half', 'hand', 'hang', 'happy', 'happy', 'hard', 'have', 'he', 'head', 'health', 'heart', 'heat', 'heavy', 'help', 'her', 'here', 'high', 'him', 'history', 'hit', 'hold', 'home', 'home', 'hospital', 'hotel', 'hour', 'house', 'how', 'human', 'hundred', 'husband', 'i', 'idea', 'if', 'image', 'imagine', 'impact', 'in', 'include', 'increase', 'individual', 'industry', 'information', 'inside', 'institution', 'interest', 'international', 'interview', 'investment', 'issue', 'it', 'item', 'its', 'job', 'join', 'keep', 'key', 'kid', 'kill', 'kind', 'kitchen', 'know', 'knowledge', 'land', 'language', 'large', 'late', 'laugh', 'law', 'lawyer', 'lay', 'lead', 'leader', 'learn', 'least', 'left', 'leg', 'legal', 'less', 'let', 'letter', 'letter', 'level', 'lie', 'life', 'light', 'like', 'likely', 'line', 'list', 'listen', 'little', 'local', 'local', 'long', 'loss', 'lot', 'love', 'low', 'machine', 'magazine', 'major', 'majority', 'make', 'man', 'manage', 'management', 'manager', 'many', 'market', 'marriage', 'material', 'matter', 'maybe', 'measure', 'media', 'medical', 'meet', 'meeting', 'member', 'memory', 'mention', 'message', 'method', 'middle', 'might', 'military', 'mind', 'minute', 'miss', 'mission', 'model', 'modern', 'moment', 'money', 'month', 'morning', 'most', 'mother', 'mouth', 'move', 'movement', 'movie', 'music', 'must', 'name', 'nation', 'national', 'natural', 'nature', 'near', 'necessary', 'need', 'network', 'new', 'news', 'newspaper', 'next', 'nice', 'night', 'no', 'none', 'north', 'not', 'note', 'nothing', 'notice', 'now', 'number', 'off', 'offer', 'office', 'officer', 'official', 'oh', 'oil', 'old', 'one', 'only', 'operation', 'opportunity', 'option', 'order', 'organization', 'other', 'others', 'others', 'out', 'outside', 'over', 'owner', 'page', 'pain', 'painting', 'paper', 'parent', 'part', 'participant', 'particular', 'partner', 'party', 'past', 'patient', 'pattern', 'pay', 'peace', 'people', 'people', 'performance', 'perhaps', 'period', 'person', 'personal', 'phone', 'physical', 'pick', 'picture', 'piece', 'place', 'plan', 'plant', 'play', 'player', 'point', 'police', 'policy', 'political', 'politics', 'poor', 'popular', 'population', 'position', 'positive', 'possible', 'power', 'practice', 'prepare', 'present', 'president', 'president', 'pressure', 'pretty', 'price', 'private', 'problem', 'process', 'product', 'production', 'professional', 'professor', 'program', 'project', 'property', 'prove', 'public', 'pull', 'purpose', 'push', 'put', 'quality', 'question', 'race', 'radio', 'raise', 'range', 'rate', 'reach', 'read', 'ready', 'real', 'reality', 'reason', 'receive', 'record', 'record', 'red', 'region', 'relationship', 'religious', 'remain', 'remove', 'report', 'republican', 'research', 'resource', 'respond', 'response', 'responsibility', 'rest', 'result', 'return', 'reveal', 'risk', 'road', 'rock', 'role', 'room', 'rule', 'run', 'safe', 'save', 'say', 'scene', 'school', 'science', 'science', 'scientist', 'score', 'sea', 'season', 'seat', 'second', 'section', 'security', 'seek', 'sell', 'send', 'send', 'senior', 'sense', 'series', 'serve', 'service', 'seven', 'several', 'sex', 'sexual', 'shake', 'share', 'she', 'shoot', 'short', 'shot', 'should', 'shoulder', 'show', 'side', 'sign', 'significant', 'similar', 'simple', 'sing', 'single', 'sister', 'sit', 'site', 'situation', 'six', 'size', 'skill', 'skin', 'skin', 'small', 'smile', 'social', 'social', 'social', 'social', 'social', 'society', 'soldier', 'somebody', 'someone', 'something', 'son', 'song', 'sort', 'source', 'south', 'southern', 'southern', 'space', 'speak', 'speak', 'special', 'specific', 'speech', 'spend', 'sport', 'spring', 'staff', 'stage', 'stand', 'standard', 'star', 'start', 'state', 'statement', 'station', 'stay', 'step', 'still', 'stock', 'stop', 'store', 'story', 'strategy', 'street', 'structure', 'student', 'stuff', 'style', 'success', 'such', 'summer', 'support', 'support', 'surface', 'system', 'table', 'take', 'task', 'tax', 'teacher', 'team', 'technology', 'television', 'tell', 'ten', 'term', 'test', 'thank', 'that', 'then', 'theory', 'there', 'thing', 'think', 'third', 'this', 'thought', 'threat', 'three', 'three', 'through', 'throw', 'time', 'today', 'tonight', 'top', 'total', 'tough', 'town', 'trade', 'traditional', 'training', 'travel', 'treat', 'treatment', 'tree', 'tree', 'trial', 'trip', 'trouble', 'trouble', 'true', 'truth', 'try', 'tv', 'tv', 'tv', 'tv', 'two', 'type', 'unit', 'unit', 'up', 'use', 'value', 'victim', 'view', 'violence', 'visit', 'voice', 'vote', 'wait', 'wall', 'want', 'war', 'watch', 'water', 'way', 'weapon', 'wear', 'week', 'weight', 'weight', 'weight', 'west', 'western', 'what', 'when', 'where', 'while', 'white', 'who', 'whole', 'why', 'wide', 'wife', 'wife', 'wind', 'window', 'window', 'wish', 'woman', 'wonder', 'word', 'work', 'worker', 'world', 'worry', 'would', 'write', 'writer', 'wrong', 'yard', 'year', 'yes', 'young'],

'ADJECTIVE':
['able', 'about', 'above', 'accept', 'according', 'adult', 'after', 'ago', 'all', 'alone', 'around', 'artist', 'available', 'away', 'baby', 'back', 'bad', 'beat', 'beautiful', 'best', 'best', 'better', 'better', 'better', 'big', 'black', 'blue', 'born', 'budget', 'business', 'by', 'capital', 'center', 'central', 'certain', 'chance', 'choice', 'civil', 'class', 'clear', 'cold', 'color', 'commercial', 'common', 'country', 'couple', 'cover', 'create', 'cultural', 'current', 'cut', 'dark', 'dead', 'deep', 'democratic', 'different', 'difficult', 'down', 'dream', 'early', 'east', 'easy', 'economic', 'economy', 'eight', 'else', 'entire', 'environmental', 'even', 'ever', 'executive', 'expert', 'fail', 'family', 'far', 'fast', 'federal', 'feeling', 'final', 'financial', 'fine', 'first', 'foreign', 'former', 'forward', 'free', 'front', 'full', 'future', 'game', 'garden', 'general', 'go', 'good', 'great', 'green', 'half', 'happy', 'hard', 'head', 'heavy', 'here', 'high', 'hit', 'home', 'hospital', 'hot', 'huge', 'human', 'important', 'in', 'individual', 'inside', 'interesting', 'international', 'it', 'just', 'key', 'land', 'large', 'last', 'late', 'later', 'left', 'legal', 'level', 'likely', 'little', 'local', 'long', 'low', 'main', 'many', 'material', 'maybe', 'medical', 'middle', 'might', 'military', 'model', 'modern', 'much', 'national', 'natural', 'near', 'necessary', 'new', 'next', 'nice', 'north', 'now', 'off', 'official', 'often', 'ok', 'old', 'on', 'one', 'only', 'onto', 'open', 'other', 'out', 'outside', 'over', 'own', 'paper', 'part', 'participant', 'particular', 'past', 'patient', 'pay', 'period', 'personal', 'physical', 'political', 'poor', 'popular', 'positive', 'possible', 'power', 'present', 'president', 'pretty', 'private', 'problem', 'professional', 'public', 'quality', 'rather', 'ready', 'real', 'recent', 'red', 'religious', 'republican', 'rich', 'right', 'road', 'run', 'safe', 'same', 'second', 'senior', 'series', 'serious', 'sexual', 'short', 'shot', 'side', 'significant', 'similar', 'simple', 'single', 'skill', 'small', 'so', 'social', 'something', 'sometimes', 'soon', 'sound', 'south', 'southern', 'special', 'specific', 'standard', 'state', 'still', 'stock', 'street', 'strong', 'subject', 'successful', 'sure', 'term', 'then', 'third', 'through', 'together', 'top', 'total', 'tough', 'toward', 'traditional', 'trial', 'trip', 'true', 'under', 'unit', 'up', 'various', 'very', 'well', 'west', 'western', 'whatever', 'white', 'whole', 'wide', 'within', 'wrong', 'young'],

'ADVERB':
['about', 'above', 'according', 'across', 'actually', 'after', 'again', 'ago', 'ahead', 'all', 'almost', 'alone', 'along', 'already', 'also', 'always', 'any', 'around', 'as', 'away', 'back', 'bad', 'because', 'before', 'behind', 'best', 'better', 'beyond', 'big', 'but', 'by', 'certainly', 'chance', 'clear', 'clearly', 'dead', 'deep', 'different', 'down', 'each', 'early', 'east', 'easy', 'either', 'else', 'enough', 'especially', 'even', 'ever', 'exactly', 'far', 'fast', 'finally', 'fine', 'first', 'forward', 'free', 'full', 'general', 'great', 'half', 'happen', 'hard', 'heavy', 'here', 'high', 'home', 'how', 'however', 'in', 'indeed', 'inside', 'instead', 'item', 'just', 'large', 'last', 'late', 'later', 'later', 'least', 'left', 'less', 'little', 'local', 'low', 'main', 'maybe', 'more', 'most', 'much', 'natural', 'near', 'nearly', 'never', 'new', 'next', 'nice', 'no', 'none', 'north', 'not', 'nothing', 'now', 'off', 'often', 'on', 'once', 'only', 'other', 'out', 'outside', 'over', 'part', 'particularly', 'past', 'perhaps', 'pm', 'pm', 'pretty', 'probably', 'quickly', 'quite', 'rather', 'real', 'really', 'recently', 'say', 'second', 'serious', 'several', 'short', 'simply', 'since', 'small', 'so', 'some', 'something', 'sometimes', 'soon', 'sound', 'south', 'still', 'strong', 'suddenly', 'sure', 'than', 'that', 'the', 'then', 'there', 'this', 'though', 'through', 'throughout', 'thus', 'to', 'today', 'together', 'tonight', 'too', 'top', 'true', 'under', 'up', 'upon', 'usually', 'very', 'well', 'west', 'what', 'what', 'when', 'where', 'whole', 'why', 'wide', 'with', 'within', 'without', 'wrong', 'yet'],

'PREPOSITION':
['about', 'above', 'across', 'after', 'again', 'against', 'along', 'among', 'around', 'as', 'at', 'because', 'before', 'behind', 'between', 'beyond', 'but', 'by', 'come', 'despite', 'down', 'during', 'from', 'half', 'in', 'including', 'inside', 'into', 'less', 'near', 'next', 'no', 'of', 'off', 'on', 'onto', 'out', 'outside', 'over', 'past', 'per', 'save', 'short', 'since', 'than', 'through', 'throughout', 'to', 'toward', 'under', 'until', 'up', 'upon', 'while', 'with', 'within', 'without'],

'VERB':
['accept', 'according', 'act', 'action', 'add', 'address', 'admit', 'adult', 'affect', 'age', 'agree', 'air', 'allow', 'amount', 'appear', 'apply', 'approach', 'argue', 'arm', 'arrive', 'article', 'ask', 'assume', 'at', 'attack', 'attorney', 'author', 'avoid', 'away', 'baby', 'back', 'bag', 'ball', 'bank', 'base', 'beat', 'become', 'bed', 'begin', 'believe', 'benefit', 'best', 'big', 'bill', 'bit', 'black', 'blood', 'blue', 'board', 'body', 'born', 'box', 'boy', 'break', 'bring', 'brother', 'budget', 'build', 'but', 'buy', 'call', 'campaign', 'can', 'candidate', 'card', 'career', 'carry', 'case', 'catch', 'cause', 'cell', 'center', 'chair', 'challenge', 'change', 'character', 'charge', 'choose', 'church', 'claim', 'class', 'clear', 'close', 'coach', 'color', 'come', 'common', 'company', 'compare', 'concern', 'condition', 'conference', 'congress', 'consider', 'contain', 'continue', 'control', 'cost', 'could', 'couple', 'course', 'court', 'cover', 'create', 'crime', 'culture', 'cup', 'cut', 'day', 'dead', 'debate', 'decide', 'decision', 'describe', 'design', 'despite', 'detail', 'determine', 'develop', 'die', 'difference', 'difficult', 'dinner', 'discover', 'discuss', 'disease', 'do', 'doctor', 'dog', 'door', 'down', 'draw', 'dream', 'drive', 'drop', 'drug', 'during', 'easy', 'eat', 'edge', 'effect', 'effort', 'end', 'enjoy', 'enter', 'establish', 'even', 'event', 'evidence', 'example', 'exist', 'expect', 'experience', 'explain', 'eye', 'face', 'factor', 'fail', 'fall', 'father', 'fear', 'feel', 'feeling', 'field', 'fight', 'figure', 'fill', 'film', 'find', 'fine', 'finger', 'finish', 'floor', 'focus', 'follow', 'foot', 'force', 'forget', 'form', 'forward', 'free', 'friend', 'front', 'fund', 'game', 'garden', 'gas', 'general', 'get', 'girl', 'give', 'glass', 'glass', 'go', 'goal', 'ground', 'group', 'grow', 'guess', 'gun', 'guy', 'hair', 'half', 'hand', 'hang', 'happen', 'happy', 'have', 'head', 'hear', 'heart', 'heavy', 'high', 'history', 'hit', 'hold', 'home', 'hope', 'hot', 'human', 'husband', 'identify', 'image', 'imagine', 'impact', 'improve', 'in', 'include', 'including', 'increase', 'indicate', 'interest', 'interesting', 'interview', 'involve', 'issue', 'item', 'job', 'join', 'keep', 'key', 'kid', 'kill', 'kitchen', 'know', 'knowledge', 'land', 'language', 'laugh', 'law', 'lawyer', 'lay', 'lead', 'learn', 'leave', 'leg', 'less', 'let', 'let', 'letter', 'level', 'lie', 'like', 'line', 'list', 'listen', 'live', 'long', 'lose', 'lot', 'love', 'low', 'machine', 'main', 'maintain', 'make', 'manage', 'market', 'material', 'matter', 'may', 'mean', 'mean', 'measure', 'meet', 'mention', 'message', 'method', 'middle', 'mind', 'minute', 'miss', 'mission', 'model', 'mouth', 'move', 'music', 'must', 'nature', 'near', 'network', 'new', 'new', 'news', 'newspaper', 'night', 'north', 'note', 'notice', 'number', 'occur', 'off', 'office', 'officer', 'oh', 'on', 'one', 'option', 'order', 'other', 'others', 'out', 'over', 'page', 'pain', 'painting', 'paper', 'parent', 'part', 'partner', 'party', 'pass', 'past', 'pattern', 'pay', 'peace', 'people', 'perform', 'period', 'person', 'phone', 'pick', 'picture', 'piece', 'plan', 'plant', 'play', 'police', 'policy', 'politics', 'position', 'power', 'practice', 'prepare', 'pressure', 'pretty', 'prevent', 'price', 'process', 'produce', 'product', 'program', 'project', 'property', 'protect', 'prove', 'prove', 'provide', 'pull', 'push', 'put', 'question', 'race', 'radio', 'raise', 'range', 'rate', 'rather', 'reach', 'read', 'ready', 'realize', 'reason', 'receive', 'recognize', 'reduce', 'reflect', 'relate', 'remain', 'remember', 'remove', 'report', 'represent', 'require', 'research', 'resource', 'respond', 'result', 'return', 'reveal', 'rich', 'rise', 'risk', 'room', 'run', 'run', 'safe', 'save', 'say', 'scene', 'school', 'science', 'score', 'season', 'seat', 'second', 'section', 'see', 'seek', 'seem', 'sell', 'send', 'sense', 'serve', 'service', 'set', 'sex', 'shake', 'share', 'shoot', 'short', 'shot', 'shot', 'should', 'should', 'should', 'shoulder', 'show', 'side', 'simple', 'sing', 'single', 'sister', 'sit', 'size', 'skin', 'small', 'smile', 'soldier', 'something', 'source', 'south', 'space', 'speak', 'special', 'speech', 'spend', 'sport', 'spring', 'spring', 'spring', 'spring', 'staff', 'stage', 'stand', 'star', 'state', 'station', 'stay', 'step', 'stock', 'stop', 'store', 'story', 'street', 'structure', 'study', 'stuff', 'style', 'suffer', 'suggest', 'summer', 'support', 'surface', 'table', 'take', 'talk', 'task', 'teach', 'team', 'television', 'tell', 'tend', 'term', 'test', 'thing', 'think', 'third', 'thought', 'thought', 'throw', 'throw', 'time', 'top', 'total', 'tough', 'trade', 'training', 'travel', 'treat', 'tree', 'trial', 'trip', 'trouble', 'true', 'truth', 'try', 'turn', 'type', 'understand', 'up', 'use', 'value', 'view', 'violence', 'visit', 'vote', 'wait', 'walk', 'wall', 'want', 'war', 'way', 'wear', 'weight', 'west', 'while', 'white', 'wife', 'will', 'win', 'wind', 'window', 'wish', 'woman', 'wonder', 'word', 'world', 'worry', 'write', 'wrong', 'yard', 'yes', 'you', 'young'],

'INTERJECTION':
['action', 'attention', 'away', 'ball', 'boy', 'brother', 'by', 'come', 'enough', 'exactly', 'fact', 'fast', 'good', 'great', 'here', 'indeed', 'just', 'later', 'man', 'morning', 'my', 'nice', 'night', 'not', 'now', 'oh', 'out', 'over', 'peace', 'period', 'pull', 'quite', 'rather', 'really', 'result', 'same', 'say', 'score', 'see', 'so', 'sound', 'standard', 'sure', 'there', 'this', 'time', 'tough', 'way', 'well', 'what', 'whatever', 'when', 'why', 'word', 'yeah', 'yes'],

'CONJUNCTION':
['after', 'against', 'all', 'although', 'and', 'as', 'because', 'before', 'both', 'but', 'choose', 'either', 'else', 'how', 'however', 'if', 'nor', 'not', 'now', 'once', 'only', 'or', 'save', 'since', 'so', 'than', 'that', 'then', 'though', 'until', 'when', 'where', 'whether', 'while', 'without', 'yet'],

'PRONOUN':
['all', 'another', 'any', 'anyone', 'anything', 'both', 'certain', 'each', 'either', 'enough', 'everybody', 'everyone', 'everything', 'few', 'he', 'her', 'herself', 'him', 'him', 'himself', 'his', 'his', 'it', 'its', 'itself', 'little', 'many', 'me', 'more', 'most', 'much', 'myself', 'none', 'nothing', 'one', 'same', 'she', 'some', 'somebody', 'someone', 'something', 'such', 'that', 'them', 'themselves', 'there', 'these', 'they', 'this', 'those', 'us', 'we', 'what', 'whatever', 'when', 'where', 'whether', 'which', 'who', 'whom', 'whose', 'you', 'yourself'],

'NUMERAL':
['eight', 'five', 'four', 'hundred', 'million', 'one', 'seven', 'six', 'ten', 'thousand', 'three', 'two']
}
